### ISSUE TITLE
'Wait for wildfly to start' task gets stuck when using journald

### ISSUE THREAD

**Issue by onitake** [inkatze/wildfly#67]
The task in configure.yml that checks for a running wildfly instance doesn't work when logging only to the systemd journal and not log files on disk:
```
    - name: Wait for wildfly to start
      wait_for:
        path: "{{ wildfly_server_log }}"
        search_regex: 'started in'
```

It would be better to check for service state instead, or, alternatively, consult the journal.
